/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

public class Simulation {

    

    public static void main(String[] args) {
        System.out.println("WTF");
    }
}
